service: reconcilator

custom:
  bucket: sesreceivezuoraemailbody
  bucketRef: S3BucketSesreceivezuoraemailbody

provider:
  name: aws
  runtime: nodejs12.x
  stage: preprod
  region: us-west-2
  role: arn:aws:iam::587579738241:role/adminlambda
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  reconcile:
    handler: handler.processZuoraEmail
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*

resources:
  Resources:
    S3EMailBucketPermissions:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: 
          Ref: ${self:custom.bucketRef}
        PolicyDocument:
          Statement:
            - Principal: 
                Service: "ses.amazonaws.com"
              Action:
                - s3:PutObject
              Effect: Allow
              Sid: "AllowSESPuts"
              Resource: 
                Fn::Join: ['', ['arn:aws:s3:::', Ref: "${self:custom.bucketRef}", '/*'] ]
              Condition:
                StringEquals:
                  "aws:Referer": { Ref: AWS::AccountId }          